name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:[
    {
        "key": "datr",
        "value": "cXvhZ8QOHLfHTxGUxIIu_xXP",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.227Z",
        "lastAccessed": "2025-04-21T08:27:58.232Z"
    },
    {
        "key": "sb",
        "value": "cXvhZ8V10nwqsIgRi0d6YbBu",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.232Z",
        "lastAccessed": "2025-04-21T08:27:58.232Z"
    },
    {
        "key": "ps_l",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.232Z",
        "lastAccessed": "2025-04-21T08:27:58.232Z"
    },
    {
        "key": "ps_n",
        "value": "1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.232Z",
        "lastAccessed": "2025-04-21T08:27:58.232Z"
    },
    {
        "key": "c_user",
        "value": "61574413662720",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.232Z",
        "lastAccessed": "2025-04-21T08:27:58.232Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B664x360x2",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.232Z",
        "lastAccessed": "2025-04-21T08:27:58.232Z"
    },
    {
        "key": "locale",
        "value": "fr_FR",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.232Z",
        "lastAccessed": "2025-04-21T08:27:58.232Z"
    },
    {
        "key": "fbl_st",
        "value": "100721962%3BT%3A29084483",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.233Z",
        "lastAccessed": "2025-04-21T08:27:58.233Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A2791%3Btimestamp%3A1745068995",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.233Z",
        "lastAccessed": "2025-04-21T08:27:58.233Z"
    },
    {
        "key": "fr",
        "value": "1goJ6tA9lxxQNOsQl.AWe-8HlIUNMUf2jn7sCopqIdLqkDXUzqeeOSZUZB_7pxPVS7QmE.BoA6PH..AAA.0.0.BoA6PH.AWf6GqlrMsfYV5I46JxNBTpufpE",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.233Z",
        "lastAccessed": "2025-04-21T08:27:58.233Z"
    },
    {
        "key": "xs",
        "value": "33%3ATSkfWHwfe8f50g%3A2%3A1742918396%3A-1%3A-1%3A%3AAcWaYiq_n1ZssEMWn30rCgl_-ikaz3zLDGoSLfjeuQ",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2025-04-21T08:27:58.233Z",
        "lastAccessed": "2025-04-21T08:27:58.233Z"
    }
]gk
  build:


    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm start
